In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df.shape

(20800, 5)

In [5]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [6]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [7]:
###Drop Nan Values
df=df.dropna()


In [8]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [9]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [10]:
## Get the Dependent features
y=df['label']

In [11]:
X.shape

(18285, 4)

In [12]:
y.shape

(18285,)

In [13]:
import tensorflow as tf

In [14]:
tf.__version__

'2.15.0'

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [16]:
### Vocabulary size
voc_size=5000

In [17]:
messages=X.copy()

In [18]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [19]:
messages.reset_index(inplace=True)

In [20]:
messages

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [21]:
import nltk
import re
from nltk.corpus import stopwords

In [22]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [23]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [25]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [26]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [27]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[785, 80, 2948, 1468, 2941, 1596, 4902, 3872, 1904, 4800],
 [758, 2900, 1267, 200, 3573, 912, 1764],
 [884, 3002, 1453, 1451],
 [25, 2327, 2185, 961, 1555, 3720],
 [667, 3573, 1785, 1083, 4959, 1476, 3573, 4155, 3457, 4476],
 [2602,
  518,
  437,
  318,
  1376,
  3578,
  3679,
  4024,
  4394,
  4322,
  4175,
  3899,
  3556,
  246,
  1764],
 [1047, 3339, 955, 2319, 3168, 3151, 4304, 1963, 4819, 3625, 4134],
 [4815, 1407, 4108, 2404, 470, 245, 3578, 3288, 4819, 3625, 4134],
 [345, 1917, 4744, 2302, 4866, 1707, 742, 4774, 3578, 1781],
 [4738, 1921, 3834, 4907, 1784, 431, 2000, 2997],
 [2964, 125, 2930, 3568, 3140, 2063, 317, 4104, 787, 1802, 1046],
 [961, 1862, 2941, 1707, 3578, 470],
 [4505, 2487, 2653, 255, 2490, 1496, 93, 4917, 2176],
 [4852, 784, 837, 1348, 1041, 1744, 3213, 4819, 3625, 4134],
 [1626, 3325, 1385, 2021, 1647, 4819, 3625, 4134],
 [3842, 4461, 4284, 2662, 397, 2373, 3999, 2671, 1733, 3065],
 [4229, 1837, 2900],
 [3535, 426, 1453, 959, 3578, 2515, 1043, 1764],
 [1659, 20

In [28]:
corpus[1]

'flynn hillari clinton big woman campu breitbart'

In [29]:
onehot_repr[1]

[758, 2900, 1267, 200, 3573, 912, 1764]

In [30]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[ 785   80 2948 ...    0    0    0]
 [ 758 2900 1267 ...    0    0    0]
 [ 884 3002 1453 ...    0    0    0]
 ...
 [2265 2266  997 ...    0    0    0]
 [1328  470 3846 ...    0    0    0]
 [4477 1089 2738 ...    0    0    0]]


In [31]:
embedded_docs[1]

array([ 758, 2900, 1267,  200, 3573,  912, 1764,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [32]:
embedded_docs[0]

array([ 785,   80, 2948, 1468, 2941, 1596, 4902, 3872, 1904, 4800,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [33]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [34]:
len(embedded_docs),y.shape

(18285, (18285,))

In [35]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [36]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [38]:
## Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 12s 50ms/step - loss: 0.3197 - accuracy: 0.8464 - val_loss: 0.1997 - val_accuracy: 0.9160
Epoch 2/10
192/192 [==============================] - 7s 39ms/step - loss: 0.1353 - accuracy: 0.9488 - val_loss: 0.2059 - val_accuracy: 0.9153
Epoch 3/10
192/192 [==============================] - 9s 49ms/step - loss: 0.0909 - accuracy: 0.9686 - val_loss: 0.2041 - val_accuracy: 0.9128
Epoch 4/10
192/192 [==============================] - 9s 47ms/step - loss: 0.0704 - accuracy: 0.9772 - val_loss: 0.2782 - val_accuracy: 0.9080
Epoch 5/10
192/192 [==============================] - 8s 40ms/step - loss: 0.0449 - accuracy: 0.9848 - val_loss: 0.3067 - val_accuracy: 0.9047
Epoch 6/10
192/192 [==============================] - 9s 49ms/step - loss: 0.0332 - accuracy: 0.9901 - val_loss: 0.4005 - val_accuracy: 0.9084
Epoch 7/10
192/192 [==============================] - 7s 39ms/step - loss: 0.0247 - accuracy: 0.9931 - val_loss: 0.4147 - val_accuracy: 0.904

In [39]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [40]:
y_pred=model.predict(X_test)

189/189 [==============================] - 2s 7ms/step


In [41]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [42]:
from sklearn.metrics import confusion_matrix

In [43]:
confusion_matrix(y_test,y_pred)

array([[3419,    0],
       [2616,    0]])

In [96]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5675227837613919

In [97]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.57      1.00      0.72      3419
           1       1.00      0.00      0.00      2616

    accuracy                           0.57      6035
   macro avg       0.78      0.50      0.36      6035
weighted avg       0.75      0.57      0.41      6035

